#!/usr/bin/env bash
#Displays the contents of the current directory in list format.
#Only displays the part of the name after the first dash.
li=$(ls)
for i in $li;
do
	echo "$i" | cut -d '-' -f2
done

